version: '3.1'

services:

  db:
    image: library/postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: postgres
    ports:
      -  5432:5432
